# Azure Pipeline build file
# Ref: https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

# resources:
# - repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build_and_Deploy
  displayName: Build and Deploy Docker image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
