# Azure Pipeline build file
# Ref: https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

# resources:
# - repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build_and_Deploy
  displayName: Build and Deploy Docker image
  variables:
  - group: 'Release'
  jobs:
  - job: Build_and_Publish
    displayName: Build and Publish Docker image
    variables:
      myDockerRegistry: 'ServiceConnectorDockerHub'
    steps:
    - script: |
        echo dockerRegistry $(dockerRegistry)
        echo myDockerRegistry $(myDockerRegistry)
    - task: Docker@2
      displayName: Login to Docker Hub
      inputs:
        command: login
        containerRegistry: '$(myDockerRegistry)'
    - task: Docker@2
      displayName: Build and Publish image
      inputs:
        command: buildAndPush
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        containerRegistry: '$(myDockerRegistry)'
        repository: '$(dockerRepository)'
        tags: |
          $(tag)
