# Azure Pipeline build file
# Ref: https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

# resources:
# - repo: self

variables:
  tag: '$(Build.BuildId)'
  dockerRegistry: 'ServiceConnectorDockerHub'

stages:
- stage: Build_and_Deploy
  displayName: Build and Deploy Docker image
  variables:
  - group: 'Release'
  jobs:
  - job: Build_and_Publish
    displayName: Build and Publish Docker image
    steps:
    - task: Docker@2
      displayName: Login to Docker Hub
      inputs:
        command: login
        containerRegistry: 'ServiceConnectorDockerHub'
    - task: Docker@2
      displayName: Build and Publish image
      inputs:
        command: buildbuildAndPush
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        containerRegistry: $(dockerRegistry)
        repository: $(dockerRepository)
        tags: |
          $(tag)
